<footer class="container">
    <div class="row">
        <div class="span12">
            <div class="row">
                <div class="span4">
                    <ul>
                        <li>
                            Lorem ipsum dulor sit amet
                        </li>
                        <li>
                            Consectetur adipiscing elit
                        </li>
                        <li>
                            Integer molestie lorem at massa
                        </li>
                        <li>
                            Facilisis in pretium nisl aliquet
                        </li>
                    </ul>
                </div>
                <div class="span4">
                    <ul>
                        <li>
                            Lorem ipsum dolor sit amet
                        </li>
                        <li>
                            Consectetur adipiscing elit
                        </li>
                        <li>
                            Integer molestie lorem at massa
                        </li>
                        <li>
                            Facilisis in pretium nisl aliquet
                        </li>
                    </ul>
                </div>
                <div class="span4">
                     <address> <strong>Twitter, Inc.</strong><br> 795 Folsom Ave, Suite 600<br> San Francisco, CA 94107<br> <abbr title="Phone">P:</abbr> (123) 456-7890</address>
                </div>
            </div>
        </div>
    </div>
</footer>