<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>:: <?php startblock('title'); ?>Voyance<?php endblock(); ?> ::</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <?php startblock('meta') ?>
    <?php endblock(); ?>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="<?php echo asset_js('html5shiv'); ?>"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="img/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="<?php echo asset_img('front/favicon.png'); ?>">


    <?php startblock('stylesheet'); ?>
    <link href="<?php echo asset_css('front/bootstrap.min'); ?>" rel="stylesheet">
    <link href="<?php echo asset_css('front/bootstrap-responsive.min'); ?>" rel="stylesheet">
    <link href="<?php echo asset_css('front/style'); ?>" rel="stylesheet">
    <link href="<?php echo asset_css('front/customstrap'); ?>" rel="stylesheet">
    <link href="<?php echo asset_css('front/tools'); ?>" rel="stylesheet">
    <?php endblock(); ?>

    <?php startblock('javascript'); ?>
    <script type="text/javascript" src="<?php echo asset_js('jquery.min'); ?>"></script>
    <script type="text/javascript" src="<?php echo asset_js('front/bootstrap.min'); ?>"></script>
    <?php endblock(); ?>
</head>

<body>
<a id="hover-zetop" href="#" title="Retour en Haut"><img src="<?php echo assets('/img/jsicon-top.png'); ?>" alt="retour en haut automatiquement"></a>

<?php tp_flash_msg(); ?>

<a id="logo" class="hidden-phone" href="<?php echo site_url(); ?>" title="Voyance Online - Retour Accueil">
    <img src="<?php echo asset_img('logo-site.png'); ?>" alt="logo voyance online">
</a>

<?php include 'elements/navigation.phtml'; ?>

<!-- SLIDESHOW -->
<?php include 'elements/slideshow.phtml'; ?>

<div id="block-content" class="container">
	<div class="row">

		<aside id="sidebar-left" class="span3">
			<?php include 'elements/sidebar-left.phtml'; ?>
            <!-- FIN ROW -->
		</aside>
		<!-- FIN SIDEBAR -->


		<!-- CONTENEUR -->
		<section class="span9 grille-voyant">
			<?php startblock('container'); ?>
            <?php endblock(); ?>
		</section>
	</div>
</div>

<div id="footer">
    <?php include 'footer.phtml'; ?>
</div>

<?php startblock('bottom-javascript'); ?>
<script type="text/javascript" src="<?php echo asset_js('jquery.rating'); ?>"></script>
<script type="text/javascript" src="<?php echo asset_js('front/script'); ?>"></script>
<?php endblock(); ?>
</body>
</html>
